package Model;
// Generated May 13, 2020 2:57:43 PM by Hibernate Tools 4.3.1



/**
 * Bookcategorie generated by hbm2java
 */
public class Bookcategorie  implements java.io.Serializable {


     private String categorieId;
     private String categorieName;

    public Bookcategorie() {
    }

    public Bookcategorie(String categorieId, String categorieName) {
       this.categorieId = categorieId;
       this.categorieName = categorieName;
    }
   
    public String getCategorieId() {
        return this.categorieId;
    }
    
    public void setCategorieId(String categorieId) {
        this.categorieId = categorieId;
    }
    public String getCategorieName() {
        return this.categorieName;
    }
    
    public void setCategorieName(String categorieName) {
        this.categorieName = categorieName;
    }




}


