package Model;
// Generated May 13, 2020 2:57:43 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String username;
     private String firstname;
     private String lastname;
     private String passward;
     private String email;

    public Users() {
    }

	
    public Users(String username, String firstname, String lastname, String passward) {
        this.username = username;
        this.firstname = firstname;
        this.lastname = lastname;
        this.passward = passward;
    }
    public Users(String username, String firstname, String lastname, String passward, String email) {
       this.username = username;
       this.firstname = firstname;
       this.lastname = lastname;
       this.passward = passward;
       this.email = email;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPassward() {
        return this.passward;
    }
    
    public void setPassward(String passward) {
        this.passward = passward;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


