package Model;
// Generated May 13, 2020 2:57:43 PM by Hibernate Tools 4.3.1



/**
 * Withdrowbook generated by hbm2java
 */
public class Withdrowbook  implements java.io.Serializable {


     private String bookName;
     private String clientName;
     private String status;
     private String dates;

    public Withdrowbook() {
    }

	
    public Withdrowbook(String bookName, String clientName, String status) {
        this.bookName = bookName;
        this.clientName = clientName;
        this.status = status;
    }
    public Withdrowbook(String bookName, String clientName, String status, String dates) {
       this.bookName = bookName;
       this.clientName = clientName;
       this.status = status;
       this.dates = dates;
    }
   
    public String getBookName() {
        return this.bookName;
    }
    
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDates() {
        return this.dates;
    }
    
    public void setDates(String dates) {
        this.dates = dates;
    }




}


